dist:     trusty
language: python
python:   3.6

notifications:
  email:
    recipients:
      - steveri@stanford.edu
    # on_success: never # default is "change"
    # on_failure: always  # default is "always"

addons:
  apt:
    packages:
      - verilator

# install:
#   - test/test.sh install

script:
  - set -e ; # Die at first error
  - cd test;
  # 
  - echo "---ADD-CLEAN"; make clean
  - echo "---ADD-BUILD"; make build TEST=ADD
  - echo "+++ADD-RUN";   make run   TEST=ADD
  # 
  - echo "---SUB-CLEAN"; make clean
  - echo "---SUB-BUILD"; make build TEST=SUB
  - echo "+++SUB-RUN";   make run   TEST=SUB
  # 
  - echo "---MUL-CLEAN"; make clean
  - echo "---MUL-BUILD"; make build TEST=MUL
  - echo "+++MUL-RUN";   make run   TEST=MUL
