dist:     trusty
language: python
python:   3.6

notifications:
  email:
    recipients:
      - steveri@stanford.edu
    # on_success: never # default is "change"
    # on_failure: always  # default is "always"

addons:
  apt:
    packages:
      - verilator

install:
  - set -e ; # Die at first error
  - cd test
  - make clean
  - make build TEST=ADD


script:
  - set -e ; # Die at first error
  - cd test
  - make run TEST=ADD |& tee result
  - egrep '^Outright fails.* 0$' result || echo FAIL
  - egrep '^Outright fails.* 0$' result || exit 13

install:
  - set -e ; # Die at first error
  - echo "---SUB-CLEAN"; make clean
  - echo "---SUB-BUILD"; make build TEST=SUB



script:
  # 
  - echo "+++SUB-RUN";   make run   TEST=SUB |& tee result
  - egrep '^Outright fails.* 0$' result && echo FAIL
  - egrep '^Outright fails.* 0$' result && exit 13
  # 
  - echo "---MUL-CLEAN"; make clean
  - echo "---MUL-BUILD"; make build TEST=MUL
  - echo "+++MUL-RUN";   make run   TEST=MUL
