dist:     trusty
language: c
# python:   3.6

notifications:
  email:
    recipients:
      - steveri@stanford.edu
    # on_success: never # default is "change"
    # on_failure: always  # default is "always"

addons:
  apt:
    packages:
      - verilator

script:

  # Setup
  - set -e  ; # Die at first error
  - cd test ; # CD to test directory


  # Add test BUILD
  - echo 'Add test BUILD' && echo -en 'travis_fold:start:build\\r'
  - make clean; make build TEST=ADD
  - echo -en 'travis_fold:end:build\\r'

  # Add test RUN
  - make run TEST=ADD |& tee result


  # Sub test BUILD
  - echo 'Sub test BUILD' && echo -en 'travis_fold:start:build\\r'
  - make clean; make build TEST=SUB
  - echo -en 'travis_fold:end:build\\r'

  # Sub test RUN
  - make run TEST=SUB |& tee result


  # Mul test BUILD
  - echo 'Mul test BUILD' && echo -en 'travis_fold:start:build\\r'
  - make clean; make build TEST=MUL
  - echo -en 'travis_fold:end:build\\r'

  # Mul test RUN
  - make run TEST=MUL |& tee result


