dist:     trusty
language: python
python:   3.6

notifications:
  email:
    recipients:
      - steveri@stanford.edu
    # on_success: never # default is "change"
    # on_failure: always  # default is "always"

install:
  - test/test.sh install

script:
  # Current working directory: /home/travis/build/steveri/easysteps
  - set -e ; # Die at first error

  - echo "--- TEST EASYSTEPS"
  - EASYSTEPS_TOP=. test/test.sh build compare
  - /bin/rm -rf build_{before,after}

script:
  # Current working directory: /home/travis/build/steveri/easysteps
  - set -e ; # Die at first error

  - echo "--- TEST EASYSTEPS-ALT"
  - EASYSTEPS_TOP=easysteps-alt test/test.sh build compare
  - /bin/rm -rf build_{before,after}
