dist:     trusty
# language: python
# python:   3.6

notifications:
  email:
    recipients:
      - steveri@stanford.edu
    # on_success: never # default is "change"
    # on_failure: always  # default is "always"

addons:
  apt:
    packages:
      - verilator

script:

  # Fold experiments
  - echo 'Configuring...' && echo -en 'travis_fold:start:script.1\\r'
  - ./autogen.sh && ./configure
  - echo -en 'travis_fold:end:script.1\\r'


  # Setup
  - set -e  ; # Die at first error
  - cd test ; # CD to test directory



  # Add test BUILD
  - echo 'travis_fold:start:NAME'
  - make clean; make build TEST=ADD
  - echo 'travis_fold:end:NAME'

  # Add test RUN
  - make run TEST=ADD |& tee result
  - egrep '^Outright fails.* 0$' result || echo FAIL
  - egrep '^Outright fails.* 0$' result || exit 13


  # 
  - make clean
  - make TEST=SUB build
  - make TEST=SUB run |& tee result
  - egrep '^Outright fails.* 0$' result && echo FAIL
  - egrep '^Outright fails.* 0$' result && exit 13

  # 
  - make clean
  - make TEST=MUL build
  - make TEST=MUL run |& tee result
  - egrep '^Outright fails.* 0$' result && echo FAIL
  - egrep '^Outright fails.* 0$' result && exit 13
  