dist:     trusty
language: python
python:   3.6

notifications:
  email:
    recipients:
      - steveri@stanford.edu
    # on_success: never # default is "change"
    # on_failure: always  # default is "always"

# install:
#   - test/test.sh install

script:
  # Current working directory: /home/travis/build/steveri/easysteps
  - set -e ; # Die at first error
  # 
  - echo "---ADD-CLEAN"; cd test; make clean
  - echo "---ADD-BUILD"; cd test; make build TEST=ADD
  - echo "+++ADD-RUN";   cd test; make run   TEST=ADD
  # 
  - echo "---SUB-CLEAN"; cd test; make clean
  - echo "---SUB-BUILD"; cd test; make build TEST=SUB
  - echo "+++SUB-RUN";   cd test; make run   TEST=SUB
  # 
  - echo "---MUL-CLEAN"; cd test; make clean
  - echo "---MUL-BUILD"; cd test; make build TEST=MUL
  - echo "+++MUL-RUN";   cd test; make run   TEST=MUL
