name: FPU Tests

# Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# Controls when the action will run. 
on: [push]

jobs:

  # This workflow contains a single job called "FPU-Tests"
  FPU-Tests:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      # Example variable values
      #   ${{ github.event_name }} = 'push
      #   ${{ runner.os }}         = 'Linux'
      #   ${{ github.ref }}        = 'refs/heads/steveri-patch-1'
      #   ${{ github.repository }} = 'steveri/fpu'
      #   ${{ github.workspace }}  = '/home/runner/work/fpu/fpu'

      - name: Check out repository code
        uses: actions/checkout@v2

      - run: |
          echo "Job info"
          echo "Job triggered by '${{ github.event_name }}' event."
          echo "Job now running on a '${{ runner.os }}' server hosted by GitHub!"
          echo "Branch: '${{ github.ref }}' in repo '${{ github.repository }}'."

      - name: Install verilator
        run: sudo apt-get install verilator

      - name: ADD test
        run: |
          cd test
          make clean

          echo "========================================================================"
          echo "make build TEST=ADD"
          echo "========================================================================"
          make build TEST=ADD

          echo "========================================================================"
          echo "make run TEST=ADD"
          echo "========================================================================"
          make run TEST=ADD

      - name: SUB test
        run: |
          cd test
          make clean

          echo "========================================================================"
          echo "make build TEST=SUB"
          echo "========================================================================"
          make build TEST=SUB

          echo "========================================================================"
          echo "make run TEST=SUB"
          echo "========================================================================"
          make run TEST=SUB

      - name: MUL test
        run: |
          cd test
          make clean

          echo "========================================================================"
          echo "make build TEST=MUL"
          echo "========================================================================"
          make build TEST=MUL

          echo "========================================================================"
          echo "make run TEST=MUL"
          echo "========================================================================"
          make run TEST=MUL
