name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      # E.g.
      #   ${{ github.event_name }} = 'push
      #   ${{ runner.os }}         = 'Linux'
      #   ${{ github.ref }}        = 'refs/heads/steveri-patch-1'
      #   ${{ github.repository }} = 'steveri/fpu'
      #   ${{ github.workspace }}  = '/home/runner/work/fpu/fpu'

      - name: INFO
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "This job's status is '${{ job.status }}'."
